microsoft/configmgr-hub

objects/CMPivotQuery/Information on Windows cumulative updates
=> Pull request with type [CREATE] for user [PanuSaukko] and object type [CMPivotQuery] - titled [Information on Windows cumulative updates]

objects/Script/Trigger Client Baseline Evaluation.ps1
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [Script] - titled [Trigger Client Baseline Evaluation]

objects/ConfigurationItem/Feature Update - SetupDiag Inventory.xml
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [ConfigurationItem] - titled [Feature Update - SetupDiag Inventory]

objects/CMPivotQuery/Get Edge Update Policy
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [CMPivotQuery] - titled [Get Edge Update Policy]

objects/CMPivotQuery/Clients without Boundary
=> Pull request with type [CREATE] for user [svschmit] and object type [CMPivotQuery] - titled [Clients without Boundary]

objects/CMPivotQuery/Average Boot Times Per Model
=> Pull request with type [CREATE] for user [svschmit] and object type [CMPivotQuery] - titled [Average Boot Times Per Model]

objects/Script/Detect Restart.ps1
=> Pull request with type [CREATE] for user [Mhudson97] and object type [Script] - titled [Detect Restart]

objects/Script/Update logged on user GPOs.ps1
=> Pull request with type [CREATE] for user [SweJorgen] and object type [Script] - titled [Update logged on user GPOs]

objects/ConfigurationItem/CMTrace Symbolic Link.xml
=> Pull request with type [CREATE] for user [alayac] and object type [ConfigurationItem] - titled [CMTrace Symbolic Link]

objects/CMPivotQuery/Find clients with Last SMSUID Change date today
=> Pull request with type [CREATE] for user [svschmit] and object type [CMPivotQuery] - titled [Find clients with Last SMSUID Change date today]

objects/CMPivotQuery/OS - Windows Versions Summarization
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [OS - Windows Versions Summarization]

objects/ConfigurationItem/Show Seconds in System Clock.xml
=> Pull request with type [CREATE] for user [MrWyss-MSFT] and object type [ConfigurationItem] - titled [Show Seconds in System Clock]

objects/CMPivotQuery/Get Battery % for all Users
=> Pull request with type [CREATE] for user [ITzeek] and object type [CMPivotQuery] - titled [Get Battery % for all Users]

objects/Script/Copy Missing File to Device.ps1
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [Script] - titled [Copy Missing File to Device]

objects/CMPivotQuery/Find Devices with Missing File
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [CMPivotQuery] - titled [Find Devices with Missing File]

objects/CMPivotQuery/Summarize Windows Client OS Editions
=> Pull request with type [CREATE] for user [merlinfrombelgium] and object type [CMPivotQuery] - titled [Summarize Windows Client OS Editions]

objects/CMPivotQuery/List local administrator accounts
=> Pull request with type [CREATE] for user [merlinfrombelgium] and object type [CMPivotQuery] - titled [List local administrator accounts]

objects/Script/Rename Computer.ps1
=> Pull request with type [CREATE] for user [merlinfrombelgium] and object type [Script] - titled [Rename Computer]

objects/Script/Remove local admin.ps1
=> Pull request with type [CREATE] for user [merlinfrombelgium] and object type [Script] - titled [Remove local admin]

objects/Script/Add local administrator.ps1
=> Pull request with type [CREATE] for user [merlinfrombelgium] and object type [Script] - titled [Add local administrator]

objects/ConfigurationItem/CI - Audit PowerShell 2.0 Host usage.xml
=> Pull request with type [CREATE] for user [kimoppalfens] and object type [ConfigurationItem] - titled [CI - Audit PowerShell 2.0 Host usage]

objects/Script/2012R2InstallWSUSwPreloadedSUSDB.ps1
=> Pull request with type [CREATE] for user [WSUSN3RD] and object type [Script] - titled [2012R2InstallWSUSwPreloadedSUSDB]

objects/Script/2016orlater-InstallWSUSwPreloadedSUSDB.ps1
=> Pull request with type [CREATE] for user [WSUSN3RD] and object type [Script] - titled [2016orlater-InstallWSUSwPreloadedSUSDB]

objects/Script/Set-CM Client Logging Option.ps1
=> Pull request with type [CREATE] for user [gwblok] and object type [Script] - titled [Set-CM Client Logging Option]

objects/Script/Enable or Disable Local Administrator Account.ps1
=> Pull request with type [CREATE] for user [AdamGrossTX] and object type [Script] - titled [Enable or Disable Local Administrator Account]

objects/Script/Get-RebootHistory.ps1
=> Pull request with type [CREATE] for user [hkystar35] and object type [Script] - titled [Get-RebootHistory]

objects/CMPivotQuery/Teams versions
=> Pull request with type [CREATE] for user [PanuSaukko] and object type [CMPivotQuery] - titled [Teams versions]

objects/Script/Odometer.ps1
=> Pull request with type [CREATE] for user [philjorgensen] and object type [Script] - titled [Odometer]

CODEOWNERS
order matters, also restricting to smaller team for codeowners.
=> Update CODEOWNERS - remove ConfigMgr team

objects/CMPivotQuery/Show Connected USB Audio Devices
=> Pull request with type [CREATE] for user [smwagner28] and object type [CMPivotQuery] - titled [Show Connected USB Audio Devices]

objects/ConsoleExtension/Right Click Tools.json
=> Pull request with type [UPDATE] for user [bryand-recastsoftware] and object type [ConsoleExtension] - titled [Right Click Tools]

objects/CMPivotQuery/Use strcat() to combine two string columns
=> Pull request with type [CREATE] for user [matbe] and object type [CMPivotQuery] - titled [Use strcat() to combine two string columns]

objects/ConsoleExtension/Right Click Tools-CodeSign-Policy.xml
=> Update Right Click Tools-CodeSign-Policy.xml

objects/CMPivotQuery/List - Wireless Adapter Info
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [List - Wireless Adapter Info]

objects/CMPivotQuery/Summarize - PowerShell Versions
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [Summarize - PowerShell Versions]

objects/Script/Start-WindowsCleanup.ps1
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [Script] - titled [Start-WindowsCleanup]

objects/CMPivotQuery/Summarize - Inactivity Lockout Timeout
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [Summarize - Inactivity Lockout Timeout]

objects/CMPivotQuery/Summarize - Windows OS Versions
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [Summarize - Windows OS Versions]

objects/Script/Get-Windows11Compatibility.ps1
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [Script] - titled [Get-Windows11Compatibility]

objects/Script/Get-ScheduledTaskInfo.ps1
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [Script] - titled [Get-ScheduledTaskInfo]

objects/CMPivotQuery/List - Most Recent Event
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [List - Most Recent Event]

objects/CMPivotQuery/Summarize - SMBv1 Client Audit
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [CMPivotQuery] - titled [Summarize - SMBv1 Client Audit]

objects/Report/Bitlocker - Compliance by Collection.rdl
=> Pull request with type [CREATE] for user [Ioan-Popovici] and object type [Report] - titled [Bitlocker - Compliance by Collection]
